# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         MKDoc-Authz
version:      0.1
version_from: lib/MKDoc/Authz.pm
installdirs:  site
requires:
    File::Touch:                   0
    MKDoc::Core:                   0.7
    MKDoc::SQL:                    0.6
    Petal:                         2.07
    Scalar::Util:                  0
    Test::Harness:                 2.00

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
